# UAV Detection Image Dataset 🚀, Custom License
# Dataset hosted on Roboflow
# Documentation: https://universe.roboflow.com/uav-i6z6x/uav-detection-zlcin

# Directory structure and dataset paths
path: ../datasets/UAVDetection
train: train/images
val: valid/images
test: test/images

# Classes
names:
  0: drone

# Download script/URL
download: |
  import os
  import configparser
  from pathlib import Path

  # Load settings from the INI file
  config = configparser.ConfigParser()
  config.read('config.ini')
  roboflow_url = config['Settings']['roboflow_url']

  # Set the directory for dataset root
  dir = Path(yaml['path'])
  dir.mkdir(parents=True, exist_ok=True)

  # Check if the ZIP file already exists
  zip_path = dir / "roboflow.zip"
  if not zip_path.exists():
      os.system(f'curl -L "{roboflow_url}" > {zip_path}')
      os.system(f'unzip -q {zip_path} -d {dir}')
  else:
      print("Dataset zip file already exists. Skipping download.")